### PR TITLE
Update LazyMan URLs.

### PR DESCRIPTION
**Pull request by evilsparc**
Fixes MLB postseason streams and aligns both URLs with latest desktop release.

### CODE REVIEW

**Comment by evilsparc** [comment]
I believe so but I haven’t tried it without the hosts edits. My understanding is that the LazyMan URLs are used to retrieve an m3u8 which contains a video element pointing to the MLB/NHL steaming service (and as such the hosts edits are still required). What I can’t fully explain is why the sub domain was dropped but there has been an update pushed to the desktop client in the last 12 hours or so that seems to do the same thing (no source code to review yet to see if that is 100% accurate). I thought it was interesting that the request url for the nhl service was pointing directly to nhl servers, but then realized that if this is running from a machine with proper hosts edits, it’s going to go redirect to lazyman anyway. Hope this helps.

**Comment by nomego** [comment]
According to https://github.com/nomego/Lazyman.bundle/issues/30#issuecomment-340281298 we should now follow https://www.reddit.com/r/LazyMan/comments/79gtvd/if_lazyman_can_not_update_your_hosts_file/ which says the IP for the hosts file is the one where powersports.ml is hosted at.

**Comment by evilsparc** [comment]
I just saw the new url over on reddit right as you posted your last comment. I'll update my PR to reflect the new address. Haven't tested it yet so hopefully that's why.

**Comment by evilsparc** [comment]
Tested with the updated URL but unfortunately the issue from #30 is still occurring. I'm guessing something changed with the nhl stats/schedule api site. Haven't had a chance to browse through the updated desktop source to see how they are working around this. If I don't find it in the next 15 minutes I probably won't be able to get to it until tomorrow sometime. Again, (and I could be wrong here but) I don't think it's related to the url stuff (although I'm glad we're working on updating it) as the error is occurring before the plugin ever reaches out to Lazyman servers for the m3u8.

**Comment by nomego** [comment]
Well the stats api error from #30 should be fixed with my last commit about 45 minutes ago.

**Comment by evilsparc** [comment]
Right... sorry. Hadn’t rolled your latest commit in before I tested.
Hopefully the combination of your fixes and the url updates make everything
happy again!

**Comment by evilsparc** [comment]
I have verified that your fixes and the url edits from my PR seem to be working nicely. Tested a live game and recap from each sport. No issues to report. Let me know if there's anything else you'd like to see before merging.

**Comment by evilsparc** [comment]
I also looked into your question about whether or not the hosts files need to be edited and it appears that it is still required. I did a simple comment out of the entries in my hosts file and streams failed (and then re-enabled to have them start up again). Maybe something to look into further a little bit later on but until then the edits in this PR have been tested and seem to be working fine with the recommended system configuration.

**Comment by nomego** [comment]
Great, thanks!

**Pull request merged**
