### PR TITLE
Fix MLB issues (wrong uri, bad metadata checks), Fix NHL issue w/ URL, formatting

### PR DESCRIPTION
**Pull request by chiefy**
- fixes MLB issues

### CODE REVIEW

**Comment by chiefy** [comment]
@nomego buuump

**Comment by fkick** [comment]
This pull fixes the "Game Feed Expired" issues I've been seeing with NHL in issue #75

**Comment by nomego** [comment]
This needs to be split into multiple PRs.
If you drop the formatting and just highlight the fixes we can start by merging that.

**Comment by chiefy** [comment]
@nomego https://github.com/nomego/Lazyman.bundle/pull/72/files?utf8=%E2%9C%93&diff=unified&w=1 <- ignore whitespace.

**Comment by chiefy** [comment]
@nomego this is still working for me and some other people using my fork, can we get this merged?

**Pull request closed without merging**
